services:
  postgres:
    container_name: forgefit-postgres
    image: postgres:18
    environment:
      POSTGRES_DB: forgefit
      POSTGRES_USER: forgefit
      POSTGRES_PASSWORD: forgefit
    volumes:
      - forgefit-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - forgefit-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forgefit"]
      interval: 10s
      timeout: 5s
      retries: 5

  forgefit-backend:
    container_name: forgefit-backend
    image: forgefit-backend:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/forgefit
      SPRING_DATASOURCE_USERNAME: forgefit
      SPRING_DATASOURCE_PASSWORD: forgefit
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - 8080:8080
    networks:
      - forgefit-network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  forgefit-network:
    driver: bridge

volumes:
  forgefit-postgres-data:
